/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/static/MagicDucky.glb
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { PerspectiveCamera, useGLTF } from '@react-three/drei'
import { RigidBody, vec3 } from '@react-three/rapier'
import { useDispatch, useSelector } from 'react-redux'
import { selectedClickStatus, selectedDirection, selectedJumpStatus } from '../../../features/reducers/gameConsoleReducer'
import { useFrame, useThree } from '@react-three/fiber'
import { setPlayerPosition } from '../../../features/reducers/gameReducer'
import * as THREE from "three";

export const DuckyMagicianModel = (props) => {
  const { nodes, materials } = useGLTF('static/MagicDucky.glb')
  const {mouse} = useThree()
  
  const duckyRef = useRef()
  const duckyMeshRef = useRef()

  const moveSpeed = 8

  const direction = useSelector(selectedDirection)
  const jumpStatus = useSelector(selectedJumpStatus)
  const clickStatus = useSelector(selectedClickStatus)


const triggerJump = (jumpStatus, delta) =>
      jumpStatus
      ? duckyRef.current.applyImpulse({ x: delta, y: 200, z: delta }, true)
      : null


const changeDirection = (direction, delta) => 

      direction === "up"  
      ? duckyRef.current.setLinvel({x: -moveSpeed , y: delta -2, z: -mouse.x * 10  + delta}, true)
      :direction === "down" 
      ? duckyRef.current.setLinvel({x: moveSpeed,  y: delta, z: mouse.x * 10 + delta }, true)
      :direction === "right"
      ? duckyRef.current.setLinvel({x: delta,  y: delta, z: -moveSpeed, }, true)
      :direction === "left"
      ? duckyRef.current.setLinvel({x: delta,  y: delta, z: moveSpeed, }, true)
      :null
      
      
      useFrame(({mouse, camera, ...state}, delta) => {
        const duckyPos = duckyMeshRef.current.parent?.position 
        // state.camera.position.lerp({x: 4 + duckyPos.x, y: 2 + duckyPos.y - mouse.y, z: duckyPos.z}, 0.05)
        camera.position.x = THREE.MathUtils.lerp(duckyPos.x, duckyPos.x + 42, 0.1)
        camera.position.y = THREE.MathUtils.lerp(duckyPos.y, duckyPos.y + 10 + 5 * mouse.y, 0.1)
        camera.position.z = THREE.MathUtils.lerp(duckyPos.z, duckyPos.z - 1, 0.1)
       camera.lookAt(duckyPos)
       camera.updateMatrixWorld()
        

        const rotationOffset = (Math.PI/ 8 * mouse.x  ) -0.9
        const midOffset = (Math.PI/ 2) - 0.69
        duckyRef?.current?.setRotation({x: rotationOffset  , y: -midOffset, z: -midOffset, w: -rotationOffset })

        triggerJump(jumpStatus, delta)
        if(!jumpStatus){
          changeDirection(direction, delta)
        }
        return null
      })

  return (
    
    <RigidBody 
        ref={duckyRef} 
        name='ducky'
        type="dynamic"
        colliders="cuboid"
        density={500}
        position={[250, 2, 10]}
        scale={0.025} 
        >
        <mesh 
          ref={duckyMeshRef}   
          geometry={nodes['19-Float_WitchDuck'].geometry} 
          material={materials['fallback Material']} 
          />
    </RigidBody>
  )
}

useGLTF.preload('/MagicDucky.glb')
