/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/static/singleMeshSpike.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/singleMeshSpike.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Core003.geometry} material={materials.Material__51} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/singleMeshSpike.glb')
