/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/static/skeletonEnemy.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skeletonEnemy.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.186, 0.57, 0.216]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.RightArm.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[0.186, 0.624, 0.021]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.torso.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[0.186, 0.315, 0.019]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.legs.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[0.186, 0.57, -0.175]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.leftArm.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
      <group position={[0.186, 0.88, 0.019]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.head.geometry} material={materials['fallback Material']} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/skeletonEnemy.glb')
