/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/static/Spike.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Spike.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.376, 1.895, 16.428]} rotation={[-Math.PI / 2, 0, 0]} scale={8.115}>
      </group>
      <group position={[-8.376, 2.318, 16.424]} rotation={[-Math.PI / 2, 0, 0]} scale={8.115}>
      </group>
      <group position={[-8.376, 1.882, 16.424]} rotation={[Math.PI / 2, 0, Math.PI]} scale={8.115}>
      </group>
      <group position={[-8.594, 2.1, 16.424]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={8.115}>
      </group>
      <group position={[-8.376, 2.1, 16.618]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={8.115}>
      </group>
      <group position={[-8.158, 2.1, 16.424]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={8.115}>
      </group>
      <group position={[-8.376, 2.1, 16.206]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={8.115}>
      </group>
    </group>
  )
}

useGLTF.preload('/Spike.glb')
